### ISSUE TITLE
Accessing `self.reference` redefined in a child class

### ISSUE THREAD

**Issue by flx42** [reframe-hpc/reframe#2549]
Consider the following code:
```python3
import reframe as rfm
import reframe.utility.sanity as sn

class TestParent(rfm.RunOnlyRegressionTest):
    valid_systems = ['*']
    valid_prog_environs = ['*']

    executable = "/bin/true"

    # The parent does not have anything in "reference" as the children implement the actual tests.
    reference = {
    }

    @run_before('run')
    def foo(self):
        # This function contains common code applicable to all children
        print(self.reference)
        self.all_tests = self.reference['cluster'].keys()

@rfm.simple_test
class TestChild1(TestParent):
    reference = {
        'cluster': {
            "device_to_host": (99, -0.05, 0.05, 'GB/s'),
            "host_to_device": (99, -0.05, 0.05, 'GB/s'),
        },
    }

@rfm.simple_test
class TestChild2(TestParent):
    reference = {
        'cluster': {
            "device_to_device": (9999, -0.05, 0.05, 'GB/s'),
        },
    }
```
The parent is not decorated with `@rfm.simple_test` as it is only used to share code between the child classes who defined `self.reference` with different values. The function `foo` tries to use this `self.reference` to set another variable. But this test program fails:
```console
[----------] start processing checks
[ RUN      ] TestChild2 @generic:default+builtin
[ RUN      ] TestChild1 @generic:default+builtin
{'cluster': {'device_to_device': (9999, -0.05, 0.05, 'GB/s')}}
[     FAIL ] (1/2) TestChild2 @generic:default+builtin
==> test failed during 'run': test staged in '/tmp/stage/generic/default/builtin/TestChild2'
{'cluster': {'device_to_host': (99, -0.05, 0.05, 'GB/s'), 'host_to_device': (99, -0.05, 0.05, 'GB/s')}}
[     FAIL ] (2/2) TestChild1 @generic:default+builtin
==> test failed during 'run': test staged in '/tmp/stage/generic/default/builtin/TestChild1'
[----------] all spawned checks have finished

[  FAILED  ] Ran 2/2 test case(s) from 2 check(s) (2 failure(s), 0 skipped)
[==========] Finished on Thu Jun 30 15:20:09 2022 

==============================================================================
SUMMARY OF FAILURES
------------------------------------------------------------------------------
FAILURE INFO for TestChild2 
  * Expanded name: TestChild2
  * Description: TestChild2
  * System partition: generic:default
  * Environment: builtin
  * Stage directory: /tmp/stage/generic/default/builtin/TestChild2
  * Node list: 
  * Job type: local (id=None)
  * Dependencies (conceptual): []
  * Dependencies (actual): []
  * Maintainers: []
  * Failing phase: run
  * Rerun with '-n TestChild2 -p builtin --system generic:default -r'
  * Reason: key error: 'cluster'
Traceback (most recent call last):
  File "/home/fabecassis/.local/lib/python3.10/site-packages/reframe/utility/__init__.py", line 1095, in __getitem__
    return self._lookup(key)
  File "/home/fabecassis/.local/lib/python3.10/site-packages/reframe/utility/__init__.py", line 1078, in _lookup
    raise KeyError(str(key))
KeyError: 'cluster'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fabecassis/.local/lib/python3.10/site-packages/reframe/frontend/executors/__init__.py", line 283, in _safe_call
    return fn(*args, **kwargs)
  File "/home/fabecassis/.local/lib/python3.10/site-packages/reframe/core/hooks.py", line 97, in _fn
    getattr(obj, h.__name__)()
  File "/home/fabecassis/.local/lib/python3.10/site-packages/reframe/core/hooks.py", line 32, in _fn
    func(*args, **kwargs)
  File "/tmp/test.py", line 18, in foo
    self.all_tests = self.reference['cluster'].keys()
  File "/home/fabecassis/.local/lib/python3.10/site-packages/reframe/utility/__init__.py", line 1097, in __getitem__
    return self.__missing__(key)
  File "/home/fabecassis/.local/lib/python3.10/site-packages/reframe/utility/__init__.py", line 1124, in __missing__
    raise KeyError(str(key))
KeyError: 'cluster'
------------------------------------------------------------------------------
```

It might be my python classes / python decorators knowledge is insufficient to understand what's going on, but as you can notice, `print(self.reference)` works and shows the `'cluster'` key, but `self.reference['cluster'].keys()` crashes.

**Comment by vkarak** [comment]
Yes, because although you set the `reference` through a normal dictionary, this is implicitly flattened and converted to a `ScopedDict`, which is a dictionary that applies scopes to its keys. Check [here](https://reframe-hpc.readthedocs.io/en/stable/utility_functions_reference.html?highlight=scopeddict#reframe.utility.ScopedDict) for more details.

**Comment by flx42** [comment]
Got it, being able to `print()` the dictionary and seeing the key there got me confused on why the next line was crashing, but it makes sense now. Feel free to close then if you want as it's not a bug.
