### ISSUE TITLE
Add test API methods for failing tests

### ISSUE THREAD

**Issue by ekouts** [reframe-hpc/reframe#2612]
It would be nice to have the `fail`, `fail_if` and `fail_if_no_procinfo` methods, similar to the `skip`, `skip_if` and `skip_if_no_procinfo`.

Already the test can easily make itself fail by raising any kind or exception but the message could be prettier:
```python
from reframe.core.exceptions import ReframeError

...
    @run_before('run')
    def make_it_fail(self):
        raise Exception('Failure message')

    @run_before('run')
    def make_it_fail_a_bit_more_gracefully(self):
        raise ReframeError('Failure message')
```

gives
```bash
  * Reason: exception: Failure message
Traceback (most recent call last):
  File "/Users/ekoutsaniti/repos/reframe/reframe/frontend/executors/__init__.py", line 303, in _safe_call
    return fn(*args, **kwargs)
  File "/Users/ekoutsaniti/repos/reframe/reframe/core/hooks.py", line 97, in _fn
    getattr(obj, h.__name__)()
  File "/Users/ekoutsaniti/repos/reframe/reframe/core/hooks.py", line 32, in _fn
    func(*args, **kwargs)
  File "/Users/ekoutsaniti/repos/reframe/test.py", line 22, in make_it_fail
    raise Exception('Failure message')
Exception: Failure message
```
or
```bash
  * Reason: reframe error: Failure message
```

**Comment by vkarak** [comment]
Related to #2635.
