### ISSUE TITLE
--cpu-only and --gpu-only broken in ReFrame 4

### ISSUE THREAD

**Issue by branfosj** [reframe-hpc/reframe#2764]
This uses `hello1.py` and `hello.c` from the first tutorial (https://reframe-hpc.readthedocs.io/en/stable/tutorial_basics.html). The `checks` directory contains `hello1.py` and `src/hello.c` and the contents are those files are as shown in https://reframe-hpc.readthedocs.io/en/stable/tutorial_basics.html#the-hello-world-test.

With ReFrame 4.0.2 I get:
```console
$ reframe -c checks/hello1.py -l --cpu-only
[ReFrame Setup]
  version:           4.0.2
  command:           '/rds/homes/b/branfosj/rf401/venv402/bin/reframe -c checks/hello1.py -l --cpu-only'
  launched by:       branfosj@bb-pg-login02.bb2.cluster
  working directory: '/rds/homes/b/branfosj/rf401'
  settings files:    '<builtin>'
  check search path: '/rds/homes/b/branfosj/rf401/checks/hello1.py'
  stage directory:   '/rds/homes/b/branfosj/rf401/stage'
  output directory:  '/rds/homes/b/branfosj/rf401/output'
  log files:         '/tmp/rfm-n78630i1.log'

[List of matched checks]
Found 0 check(s)

Log file(s) saved in '/tmp/rfm-n78630i1.log'
```

```console
$ reframe -c checks/hello1.py -l --gpu-only
[ReFrame Setup]
  version:           4.0.2
  command:           '/rds/homes/b/branfosj/rf401/venv402/bin/reframe -c checks/hello1.py -l --gpu-only'
  launched by:       branfosj@bb-pg-login02.bb2.cluster
  working directory: '/rds/homes/b/branfosj/rf401'
  settings files:    '<builtin>'
  check search path: '/rds/homes/b/branfosj/rf401/checks/hello1.py'
  stage directory:   '/rds/homes/b/branfosj/rf401/stage'
  output directory:  '/rds/homes/b/branfosj/rf401/output'
  log files:         '/tmp/rfm-z_tsg8_0.log'

ERROR: run session stopped: type error: '>' not supported between instances of 'NoneType' and 'int'
ERROR: Traceback (most recent call last):
  File "/rds/homes/b/branfosj/rf401/venv402/lib64/python3.6/site-packages/reframe/frontend/cli.py", line 996, in main
    testcases = list(testcases)
  File "/rds/homes/b/branfosj/rf401/venv402/lib64/python3.6/site-packages/reframe/frontend/filters.py", line 113, in _fn
    return case.check.num_gpus_per_node > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Log file(s) saved in '/tmp/rfm-z_tsg8_0.log'
```

With ReFrame 3.12.0 these work as I expect them too
```console
$ reframe -c checks/hello1.py -l --cpu-only
[ReFrame Setup]
  version:           3.12.0
  command:           '/rds/homes/b/branfosj/rf401/venv312/bin/reframe -c checks/hello1.py -l --cpu-only'
  launched by:       branfosj@bb-pg-login02.bb2.cluster
  working directory: '/rds/homes/b/branfosj/rf401'
  settings file:     '<builtin>'
  check search path: '/rds/homes/b/branfosj/rf401/checks/hello1.py'
  stage directory:   '/rds/homes/b/branfosj/rf401/stage'
  output directory:  '/rds/homes/b/branfosj/rf401/output'

[List of matched checks]
- HelloTest
Found 1 check(s)

Log file(s) saved in '/tmp/rfm-josa3561.log'
```

```console
$ reframe -c checks/hello1.py -l --gpu-only
[ReFrame Setup]
  version:           3.12.0
  command:           '/rds/homes/b/branfosj/rf401/venv312/bin/reframe -c checks/hello1.py -l --gpu-only'
  launched by:       branfosj@bb-pg-login02.bb2.cluster
  working directory: '/rds/homes/b/branfosj/rf401'
  settings file:     '<builtin>'
  check search path: '/rds/homes/b/branfosj/rf401/checks/hello1.py'
  stage directory:   '/rds/homes/b/branfosj/rf401/stage'
  output directory:  '/rds/homes/b/branfosj/rf401/output'

[List of matched checks]
Found 0 check(s)

Log file(s) saved in '/tmp/rfm-w8_8272q.log'
```

**Comment by branfosj** [comment]
If I add
```
num_gpus_per_node = 0
```
to `hello1.py` then `--cpu-only` and `--gpu-only` work as expected. However, this was not needed in ReFrame 3.12.

**Comment by branfosj** [comment]
Further testing: This broke between `4.0.0.dev1` and `4.0.0.dev2`.

**Comment by vkarak** [comment]
Yep, the default value for `num_gpus_per_node` was changed to `None` in 4.0, thus the crash. That's certainly a bug. Thanks for reporting!

**Comment by vkarak** [comment]
Merged into develop.
