### ISSUE TITLE
Hello World Test Example Gives Error "undefined reference to MPI_Bcast"

### ISSUE THREAD

**Issue by kaanolgu** [reframe-hpc/reframe#2808]
I have installed `ReFrame v3.11.0` via `spack install reframe@3.11.0` command and I have also tried cloning the main branch and installing it seperately too but on Isambard HPC login node 2 I get the following error 

```
--- rfm_HelloTest_build.err --- 
[2023-03-02T01:22:40] info: reframe: [ [31m    FAIL[0m ] (1/1) HelloTest @generic:default+builtin
[2023-03-02T01:22:40] info: reframe: ==> test failed during 'compile_wait': test staged in '/lustre/home/br-kolgu/excalibur-tests/spack-environments/isambard-cascadelake/compute-node/opt/spack/cray-rhel8-broadwell/gcc-9.2.0/reframe-3.11.0-72lwjngnajtjvitb3towubrziq2jxmdj/stage/generic/default/builtin/HelloTest'
[2023-03-02T01:22:40] verbose: reframe: ==> setup: 0.012s compile: 0.280s run: n/a sanity: n/a performance: n/a total: 0.301s
[2023-03-02T01:22:40] info: reframe: [----------] all spawned checks have finished

[2023-03-02T01:22:40] info: reframe: [ [31m FAILED [0m ] Ran 1/1 test case(s) from 1 check(s) (1 failure(s), 0 skipped)
[2023-03-02T01:22:40] info: reframe: [==========] Finished on Thu Mar  2 01:22:40 2023 
[2023-03-02T01:22:40] info: reframe: 
[2023-03-02T01:22:40] info: reframe: ==============================================================================
[2023-03-02T01:22:40] info: reframe: SUMMARY OF FAILURES
[2023-03-02T01:22:40] info: reframe: ------------------------------------------------------------------------------
[2023-03-02T01:22:40] info: reframe: FAILURE INFO for HelloTest 
[2023-03-02T01:22:40] info: reframe:   * Expanded name: HelloTest
[2023-03-02T01:22:40] info: reframe:   * Description: HelloTest
[2023-03-02T01:22:40] info: reframe:   * System partition: generic:default
[2023-03-02T01:22:40] info: reframe:   * Environment: builtin
[2023-03-02T01:22:40] info: reframe:   * Stage directory: /lustre/home/br-kolgu/excalibur-tests/spack-environments/isambard-cascadelake/compute-node/opt/spack/cray-rhel8-broadwell/gcc-9.2.0/reframe-3.11.0-72lwjngnajtjvitb3towubrziq2jxmdj/stage/generic/default/builtin/HelloTest
[2023-03-02T01:22:40] info: reframe:   * Node list: 
[2023-03-02T01:22:40] info: reframe:   * Job type: local (id=None)
[2023-03-02T01:22:40] info: reframe:   * Dependencies (conceptual): []
[2023-03-02T01:22:40] info: reframe:   * Dependencies (actual): []
[2023-03-02T01:22:40] info: reframe:   * Maintainers: []
[2023-03-02T01:22:40] info: reframe:   * Failing phase: compile_wait
[2023-03-02T01:22:40] info: reframe:   * Rerun with '-n HelloTest -p builtin --system generic:default -r'
[2023-03-02T01:22:40] info: reframe:   * Reason: build error: stdout: 'rfm_HelloTest_build.out', stderr: 'rfm_HelloTest_build.err'
--- rfm_HelloTest_build.err (first 10 lines) ---
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Bcast [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Op_create [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Pack_size [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Send [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Type_struct [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Isend [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Unpack [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Cancel [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Initialized [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Type_free [--no-allow-shlib-undefined]
--- rfm_HelloTest_build.err --- 
[2023-03-02T01:22:40] verbose: reframe: Traceback (most recent call last):
  File "/lustre/home/br-kolgu/excalibur-tests/spack-environments/isambard-cascadelake/compute-node/opt/spack/cray-rhel8-broadwell/gcc-9.2.0/reframe-3.11.0-72lwjngnajtjvitb3towubrziq2jxmdj/reframe/frontend/executors/__init__.py", line 283, in _safe_call
    return fn(*args, **kwargs)
  File "/lustre/home/br-kolgu/excalibur-tests/spack-environments/isambard-cascadelake/compute-node/opt/spack/cray-rhel8-broadwell/gcc-9.2.0/reframe-3.11.0-72lwjngnajtjvitb3towubrziq2jxmdj/reframe/core/hooks.py", line 99, in _fn
    func(obj, *args, **kwargs)
  File "/lustre/home/br-kolgu/excalibur-tests/spack-environments/isambard-cascadelake/compute-node/opt/spack/cray-rhel8-broadwell/gcc-9.2.0/reframe-3.11.0-72lwjngnajtjvitb3towubrziq2jxmdj/reframe/core/pipeline.py", line 1780, in compile_wait
    self._build_job.stderr, self._stagedir)
reframe.core.exceptions.BuildError: stdout: 'rfm_HelloTest_build.out', stderr: 'rfm_HelloTest_build.err'
--- rfm_HelloTest_build.err (first 10 lines) ---
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Bcast [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Op_create [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Pack_size [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Send [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Type_struct [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Isend [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Unpack [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Cancel [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Initialized [--no-allow-shlib-undefined]
ld.lld: error: /opt/cray/pe/libsci/20.03.1/CRAY/8.5/x86_64/lib/libsci_cray_mpi.so: undefined reference to MPI_Type_free [--no-allow-shlib-undefined]
--- rfm_HelloTest_build.err --- 

[2023-03-02T01:22:40] info: reframe: ------------------------------------------------------------------------------
[2023-03-02T01:22:40] info: reframe: Run report saved in '/home/br-kolgu/.reframe/reports/run-report.json'
[2023-03-02T01:22:40] info: reframe: Log file(s) saved in '/tmp/rfm-s_79fbxz.log'

```

**Comment by vkarak** [comment]
This does not seem like a reframe problem, at least at this point. Have you inspected the build script that was generated in the test's stage dir? You can try to make this compile by hand and see what is missing, then adapt your test accordingly.
