### ISSUE TITLE
`TypeError: can only join an iterable is` if resubmit_on_errors is not set

### ISSUE THREAD

**Issue by branfosj** [reframe-hpc/reframe#2879]
This is with ReFrame 4.2.0 (and also 4.1.0).

```
Traceback (most recent call last):
  File "/bask/projects/e/edmondac-rsg/reframe/venv-system/lib64/python3.6/site-packages/reframe/frontend/executors/__init__.py", line 317, in _safe_call
    return fn(*args, **kwargs)
  File "/bask/projects/e/edmondac-rsg/reframe/venv-system/lib64/python3.6/site-packages/reframe/core/hooks.py", line 103, in _fn
    func(obj, *args, **kwargs)
  File "/bask/projects/e/edmondac-rsg/reframe/venv-system/lib64/python3.6/site-packages/reframe/core/pipeline.py", line 2564, in run
    super().run()
  File "/bask/projects/e/edmondac-rsg/reframe/venv-system/lib64/python3.6/site-packages/reframe/core/pipeline.py", line 1998, in run
    self._job.submit()
  File "/bask/projects/e/edmondac-rsg/reframe/venv-system/lib64/python3.6/site-packages/reframe/core/schedulers/__init__.py", line 581, in submit
    return self.scheduler.submit(self)
  File "/bask/projects/e/edmondac-rsg/reframe/venv-system/lib64/python3.6/site-packages/reframe/core/schedulers/slurm.py", line 261, in submit
    rf'({"|".join(self._resubmit_on_errors)})', e.stderr
TypeError: can only join an iterable
```

I am not setting `resubmit_on_errors` and https://reframe-hpc.readthedocs.io/en/stable/config_reference.html#config.systems.partitions.sched_options.resubmit_on_errors says that this should default to `[]`. However, that is not happening. We then see the failure at https://github.com/reframe-hpc/reframe/blob/bacb1aff91852b0a8bee3f58fd6a7b938d7bb87b/reframe/core/schedulers/slurm.py#L260 when the join fails.

**Comment by vkarak** [comment]
Hi @branfosj, I think that's indeed a bug; I've encountered it at some point while working on a feature. Thanks for reporting.
